In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

In [2]:
df = pd.read_csv("bike_cleaned_data.csv")

In [14]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 8760 entries, 0 to 8759
Data columns (total 16 columns):
 #   Column                   Non-Null Count  Dtype
---  ------                   --------------  -----
 0   day                      8760 non-null   object
 1   date                     8760 non-null   int64
 2   month                    8760 non-null   int64
 3   year                     8760 non-null   int64
 4   Rented Bike Count        8760 non-null   int64
 5   Hour                     8760 non-null   int64
 6   Temperature(°C)          8760 non-null   float64
 7   Humidity(%)              8760 non-null   int64
 8   Wind speed (m/s)         8760 non-null   float64
 9   Visibility (10m)         8760 non-null   int64
 10  Solar Radiation (MJ/m2)  8760 non-null   float64
 11  Rainfall(mm)             8760 non-null   float64
 12  Snowfall (cm)            8760 non-null   float64
 13  Seasons                  8760 non-null   object
 14  Holiday                  8760 non-null   object
 15  Functioning Day          8760 non-null   object
dtypes: float64(5), int64(7), object(4)
memory usage: 1.1+ MB

In [6]:
df.columns

Index(['day', 'date', 'month', 'year', 'Rented Bike Count', 'Hour',
       'Temperature(°C)', 'Humidity(%)', 'Wind speed (m/s)',
       'Visibility (10m)', 'Solar Radiation (MJ/m2)', 'Rainfall(mm)',
       'Snowfall (cm)', 'Seasons', 'Holiday', 'Functioning Day'],
      dtype='object')

In [9]:
Q1 = df['Rented Bike Count'].quantile(0.25)
Q3 = df['Rented Bike Count'].quantile(0.75)
IQR = Q3 - Q1

# Define bounds for outliers
lower_bound = Q1 - 1.5 * IQR
upper_bound = Q3 + 1.5 * IQR

# Identify outliers
outliers_sqft = df[(df['Rented Bike Count'] < lower_bound) | (df['Rented Bike Count'] > upper_bound)]

# Displaying the number of outliers and some statistics
num_outliers = outliers_sqft.shape[0]
outliers_sqft_stats = outliers_sqft['Rented Bike Count'].describe()

num_outliers, outliers_sqft_stats

(158,
 count     158.000000
 mean     2698.873418
 std       304.303962
 min      2377.000000
 25%      2454.250000
 50%      2596.000000
 75%      2881.250000
 max      3556.000000
 Name: Rented Bike Count, dtype: float64)

In [13]:
outliers_sqft.sort_values('Rented Bike Count',ascending=False).head(10)

,day,date,month,year,Rented Bike Count,Hour,Temperature(°C),Humidity(%),Wind speed (m/s),Visibility (10m),Solar Radiation (MJ/m2),Rainfall(mm),Snowfall (cm),Seasons,Holiday,Functioning Day
4818,Tuesday,19,6,2018,3556,18,24.1,57,2.9,1301,0.56,0.0,0.0,Summer,No Holiday,Yes
4866,Thursday,21,6,2018,3418,18,27.8,43,3.0,1933,1.35,0.0,0.0,Summer,No Holiday,Yes
4650,Tuesday,12,6,2018,3404,18,24.9,53,3.6,2000,1.28,0.0,0.0,Summer,No Holiday,Yes
4842,Wednesday,20,6,2018,3384,18,27.0,55,3.1,1246,1.26,0.0,0.0,Summer,No Holiday,Yes
4458,Monday,4,6,2018,3380,18,24.4,48,1.9,1998,0.56,0.0,0.0,Summer,No Holiday,Yes
4890,Friday,22,6,2018,3365,18,29.3,27,3.4,1977,1.24,0.0,0.0,Summer,No Holiday,Yes
4554,Friday,8,6,2018,3309,18,26.2,54,2.2,1183,0.88,0.0,0.0,Summer,No Holiday,Yes
6810,Monday,10,9,2018,3298,18,25.9,42,1.1,2000,0.48,0.0,0.0,Autumn,No Holiday,Yes
6978,Monday,17,9,2018,3277,18,25.3,56,2.8,1992,0.54,0.0,0.0,Autumn,No Holiday,Yes
6858,Wednesday,12,9,2018,3256,18,27.0,44,1.4,2000,0.62,0.0,0.0,Autumn,No Holiday,Yes

In [15]:
def outlier_check_all(df):
    # Loop over all numerical columns
    numerical_columns = df.select_dtypes(include=['int64', 'float64']).columns

    for column in numerical_columns:
        Q1 = df[column].quantile(0.25)
        Q3 = df[column].quantile(0.75)
        IQR = Q3 - Q1

        # Define bounds for outliers
        lower_bound = Q1 - 1.5 * IQR
        upper_bound = Q3 + 1.5 * IQR

        # Identify outliers
        outliers = df[(df[column] < lower_bound) | (df[column] > upper_bound)]

        # Display the number of outliers and some statistics
        num_outliers = outliers.shape[0]
        outliers_stats = outliers[column].describe()

        print(f"Column: {column}")
        print(f"Number of Outliers: {num_outliers}")
        print(f"Outliers Statistics:\n{outliers_stats}")
        print(f"Top 10 Outliers in {column}:\n{outliers.sort_values(column, ascending=False).head(10)}")
        print("\n" + "="*50 + "\n")

# Call the function on the dataframe
outlier_check_all(df)

Column: date
Number of Outliers: 0
Outliers Statistics:
count    0.0
mean     NaN
std      NaN
min      NaN
25%      NaN
50%      NaN
75%      NaN
max      NaN
Name: date, dtype: float64
Top 10 Outliers in date:
Empty DataFrame
Columns: [day, date, month, year, Rented Bike Count, Hour, Temperature(°C), Humidity(%), Wind speed (m/s), Visibility (10m), Solar Radiation (MJ/m2), Rainfall(mm), Snowfall (cm), Seasons, Holiday, Functioning Day]
Index: []

==================================================

Column: month
Number of Outliers: 0
Outliers Statistics:
count    0.0
mean     NaN
std      NaN
min      NaN
25%      NaN
50%      NaN
75%      NaN
max      NaN
Name: month, dtype: float64
Top 10 Outliers in month:
Empty DataFrame
Columns: [day, date, month, year, Rented Bike Count, Hour, Temperature(°C), Humidity(%), Wind speed (m/s), Visibility (10m), Solar Radiation (MJ/m2), Rainfall(mm), Snowfall (cm), Seasons, Holiday, Functioning Day]
Index: []

==================================================

Column: year
Number of Outliers: 744
Outliers Statistics:
count     744.0
mean     2017.0
std         0.0
min      2017.0
25%      2017.0
50%      2017.0
75%      2017.0
max      2017.0
Name: year, dtype: float64
Top 10 Outliers in year:
          day  date  month  year  Rented Bike Count  Hour  Temperature(°C)  \
0      Friday     1     12  2017                254     0             -5.2
499  Thursday    21     12  2017                355    19              0.8
490  Thursday    21     12  2017                169    10             -3.0
491  Thursday    21     12  2017                243    11             -0.7
492  Thursday    21     12  2017                290    12              1.9
493  Thursday    21     12  2017                285    13              3.2
494  Thursday    21     12  2017                255    14              4.3
495  Thursday    21     12  2017                316    15              4.4
496  Thursday    21     12  2017                301    16              4.1
497  Thursday    21     12  2017                366    17              2.9

     Humidity(%)  Wind speed (m/s)  Visibility (10m)  Solar Radiation (MJ/m2)  \
0             37               2.2              2000                     0.00
499           71               0.9               923                     0.00
490           71               0.7               608                     0.67
491           62               0.7               519                     0.77
492           40               2.0              1835                     1.04
493           42               1.8              1349                     1.08
494           47               2.3               953                     0.96
495           46               1.4              1113                     0.78
496           51               1.8              1112                     0.48
497           60               1.3              1193                     0.16

     Rainfall(mm)  Snowfall (cm) Seasons     Holiday Functioning Day
0             0.0            0.0  Winter  No Holiday             Yes
499           0.0            0.8  Winter  No Holiday             Yes
490           0.0            2.1  Winter  No Holiday             Yes
491           0.0            2.0  Winter  No Holiday             Yes
492           0.0            1.9  Winter  No Holiday             Yes
493           0.0            1.8  Winter  No Holiday             Yes
494           0.0            1.6  Winter  No Holiday             Yes
495           0.0            1.0  Winter  No Holiday             Yes
496           0.0            0.9  Winter  No Holiday             Yes
497           0.0            0.8  Winter  No Holiday             Yes

==================================================

Column: Rented Bike Count
Number of Outliers: 158
Outliers Statistics:
count     158.000000
mean     2698.873418
std       304.303962
min      2377.000000
25%      2454.250000
50%      2596.000000
75%      2881.250000
max      3556.000000
Name: Rented Bike Count, dtype: float64
Top 10 Outliers in Rented Bike Count:
            day  date  month  year  Rented Bike Count  Hour  Temperature(°C)  \
4818    Tuesday    19      6  2018               3556    18             24.1
4866   Thursday    21      6  2018               3418    18             27.8
4650    Tuesday    12      6  2018               3404    18             24.9
4842  Wednesday    20      6  2018               3384    18             27.0
4458     Monday     4      6  2018               3380    18             24.4
4890     Friday    22      6  2018               3365    18             29.3
4554     Friday     8      6  2018               3309    18             26.2
6810     Monday    10      9  2018               3298    18             25.9
6978     Monday    17      9  2018               3277    18             25.3
6858  Wednesday    12      9  2018               3256    18             27.0

      Humidity(%)  Wind speed (m/s)  Visibility (10m)  \
4818           57               2.9              1301
4866           43               3.0              1933
4650           53               3.6              2000
4842           55               3.1              1246
4458           48               1.9              1998
4890           27               3.4              1977
4554           54               2.2              1183
6810           42               1.1              2000
6978           56               2.8              1992
6858           44               1.4              2000

      Solar Radiation (MJ/m2)  Rainfall(mm)  Snowfall (cm) Seasons  \
4818                     0.56           0.0            0.0  Summer
4866                     1.35           0.0            0.0  Summer
4650                     1.28           0.0            0.0  Summer
4842                     1.26           0.0            0.0  Summer
4458                     0.56           0.0            0.0  Summer
4890                     1.24           0.0            0.0  Summer
4554                     0.88           0.0            0.0  Summer
6810                     0.48           0.0            0.0  Autumn
6978                     0.54           0.0            0.0  Autumn
6858                     0.62           0.0            0.0  Autumn

         Holiday Functioning Day
4818  No Holiday             Yes
4866  No Holiday             Yes
4650  No Holiday             Yes
4842  No Holiday             Yes
4458  No Holiday             Yes
4890  No Holiday             Yes
4554  No Holiday             Yes
6810  No Holiday             Yes
6978  No Holiday             Yes
6858  No Holiday             Yes

==================================================

Column: Hour
Number of Outliers: 0
Outliers Statistics:
count    0.0
mean     NaN
std      NaN
min      NaN
25%      NaN
50%      NaN
75%      NaN
max      NaN
Name: Hour, dtype: float64
Top 10 Outliers in Hour:
Empty DataFrame
Columns: [day, date, month, year, Rented Bike Count, Hour, Temperature(°C), Humidity(%), Wind speed (m/s), Visibility (10m), Solar Radiation (MJ/m2), Rainfall(mm), Snowfall (cm), Seasons, Holiday, Functioning Day]
Index: []

==================================================

Column: Temperature(°C)
Number of Outliers: 0
Outliers Statistics:
count    0.0
mean     NaN
std      NaN
min      NaN
25%      NaN
50%      NaN
75%      NaN
max      NaN
Name: Temperature(°C), dtype: float64
Top 10 Outliers in Temperature(°C):
Empty DataFrame
Columns: [day, date, month, year, Rented Bike Count, Hour, Temperature(°C), Humidity(%), Wind speed (m/s), Visibility (10m), Solar Radiation (MJ/m2), Rainfall(mm), Snowfall (cm), Seasons, Holiday, Functioning Day]
Index: []

==================================================

Column: Humidity(%)
Number of Outliers: 0
Outliers Statistics:
count    0.0
mean     NaN
std      NaN
min      NaN
25%      NaN
50%      NaN
75%      NaN
max      NaN
Name: Humidity(%), dtype: float64
Top 10 Outliers in Humidity(%):
Empty DataFrame
Columns: [day, date, month, year, Rented Bike Count, Hour, Temperature(°C), Humidity(%), Wind speed (m/s), Visibility (10m), Solar Radiation (MJ/m2), Rainfall(mm), Snowfall (cm), Seasons, Holiday, Functioning Day]
Index: []

==================================================

Column: Wind speed (m/s)
Number of Outliers: 161
Outliers Statistics:
count    161.000000
mean       4.885093
std        0.542127
min        4.400000
25%        4.500000
50%        4.700000
75%        5.000000
max        7.400000
Name: Wind speed (m/s), dtype: float64
Top 10 Outliers in Wind speed (m/s):
            day  date  month  year  Rented Bike Count  Hour  Temperature(°C)  \
3134    Tuesday    10      4  2018                913    14             21.2
3141    Tuesday    10      4  2018                133    21             17.5
3138    Tuesday    10      4  2018               1805    18             19.7
6316    Tuesday    21      8  2018                 49     4             25.3
933      Monday     8      1  2018                146    21              0.7
3140    Tuesday    10      4  2018                336    20             19.1
1309  Wednesday    24      1  2018                140    13            -12.0
2174   Thursday     1      3  2018                375    14              1.2
3139    Tuesday    10      4  2018               1153    19             19.2
1724   Saturday    10      2  2018                132    20             -4.4

      Humidity(%)  Wind speed (m/s)  Visibility (10m)  \
3134           35               7.4              1992
3141           70               7.3              1634
3138           52               7.2              2000
6316           70               6.9               925
933            77               6.7               692
3140           58               6.1              2000
1309           25               6.0              1887
2174           36               6.0              1430
3139           55               5.8              2000
1724           19               5.8              2000

      Solar Radiation (MJ/m2)  Rainfall(mm)  Snowfall (cm) Seasons  \
3134                     1.80           0.0            0.0  Spring
3141                     0.00           0.5            0.0  Spring
3138                     0.20           0.0            0.0  Spring
6316                     0.00           0.4            0.0  Summer
933                      0.00           0.9            1.0  Winter
3140                     0.00           0.0            0.0  Spring
1309                     1.27           0.0            0.9  Winter
2174                     2.86           0.0            0.0  Spring
3139                     0.01           0.0            0.0  Spring
1724                     0.00           0.0            0.0  Winter

         Holiday Functioning Day
3134  No Holiday             Yes
3141  No Holiday             Yes
3138  No Holiday             Yes
6316  No Holiday             Yes
933   No Holiday             Yes
3140  No Holiday             Yes
1309  No Holiday             Yes
2174     Holiday             Yes
3139  No Holiday             Yes
1724  No Holiday             Yes

==================================================

Column: Visibility (10m)
Number of Outliers: 0
Outliers Statistics:
count    0.0
mean     NaN
std      NaN
min      NaN
25%      NaN
50%      NaN
75%      NaN
max      NaN
Name: Visibility (10m), dtype: float64
Top 10 Outliers in Visibility (10m):
Empty DataFrame
Columns: [day, date, month, year, Rented Bike Count, Hour, Temperature(°C), Humidity(%), Wind speed (m/s), Visibility (10m), Solar Radiation (MJ/m2), Rainfall(mm), Snowfall (cm), Seasons, Holiday, Functioning Day]
Index: []

==================================================

Column: Solar Radiation (MJ/m2)
Number of Outliers: 641
Outliers Statistics:
count    641.000000
mean       2.774290
std        0.300623
min        2.330000
25%        2.510000
50%        2.740000
75%        2.990000
max        3.520000
Name: Solar Radiation (MJ/m2), dtype: float64
Top 10 Outliers in Solar Radiation (MJ/m2):
            day  date  month  year  Rented Bike Count  Hour  Temperature(°C)  \
4165  Wednesday    23      5  2018               1167    13             20.9
4069   Saturday    19      5  2018               1865    13             21.9
4117     Monday    21      5  2018               1456    13             22.8
6205   Thursday    16      8  2018                652    13             35.1
4164  Wednesday    23      5  2018               1216    12             20.1
4405   Saturday     2      6  2018               1334    13             29.6
4861   Thursday    21      6  2018               1147    13             27.3
4717     Friday    15      6  2018               1035    13             25.3
4068   Saturday    19      5  2018               1573    12             20.5
4166  Wednesday    23      5  2018               1183    14             22.0

      Humidity(%)  Wind speed (m/s)  Visibility (10m)  \
4165           33               3.9              1853
4069           39               2.0              2000
4117           31               1.9              1923
6205           39               2.0              2000
4164           37               4.0              1910
4405           24               2.4              1873
4861           33               3.4              1921
4717           48               1.8              1935
4068           42               2.1              2000
4166           33               3.4              1966

      Solar Radiation (MJ/m2)  Rainfall(mm)  Snowfall (cm) Seasons  \
4165                     3.52           0.0            0.0  Spring
4069                     3.52           0.0            0.0  Spring
4117                     3.49           0.0            0.0  Spring
6205                     3.45           0.0            0.0  Summer
4164                     3.44           0.0            0.0  Spring
4405                     3.42           0.0            0.0  Summer
4861                     3.42           0.0            0.0  Summer
4717                     3.42           0.0            0.0  Summer
4068                     3.42           0.0            0.0  Spring
4166                     3.41           0.0            0.0  Spring

         Holiday Functioning Day
4165  No Holiday             Yes
4069  No Holiday             Yes
4117  No Holiday             Yes
6205  No Holiday             Yes
4164  No Holiday             Yes
4405  No Holiday             Yes
4861  No Holiday             Yes
4717  No Holiday             Yes
4068  No Holiday             Yes
4166  No Holiday             Yes

==================================================

Column: Rainfall(mm)
Number of Outliers: 528
Outliers Statistics:
count    528.000000
mean       2.466856
std        3.927524
min        0.100000
25%        0.500000
50%        1.000000
75%        2.500000
max       35.000000
Name: Rainfall(mm), dtype: float64
Top 10 Outliers in Rainfall(mm):
            day  date  month  year  Rented Bike Count  Hour  Temperature(°C)  \
3997  Wednesday    16      5  2018                151    13             21.8
6501    Tuesday    28      8  2018                122    21             22.9
5132     Monday     2      7  2018                 61    20             23.5
5034   Thursday    28      6  2018                596    18             20.6
6524  Wednesday    29      8  2018                 19    20             23.4
4012   Thursday    17      5  2018                 51     4             19.2
6498    Tuesday    28      8  2018                 96    18             24.3
5099     Sunday     1      7  2018                 11    11             21.2
8232     Friday     9     11  2018                  0     0             12.0
8229   Thursday     8     11  2018                 21    21             14.0

      Humidity(%)  Wind speed (m/s)  Visibility (10m)  \
3997           97               2.4               682
6501           98               2.1              1146
5132           97               0.1              1814
5034           97               0.7               222
6524           98               0.6                70
4012           98               2.4              1965
6498           97               0.8               105
5099           97               1.2               105
8232           96               3.1              1185
8229           96               4.1               292

      Solar Radiation (MJ/m2)  Rainfall(mm)  Snowfall (cm) Seasons  \
3997                     0.06          35.0            0.0  Spring
6501                     0.00          29.5            0.0  Summer
5132                     0.04          24.0            0.0  Summer
5034                     0.14          21.5            0.0  Summer
6524                     0.00          21.0            0.0  Summer
4012                     0.00          19.0            0.0  Spring
6498                     0.01          18.5            0.0  Summer
5099                     0.15          18.5            0.0  Summer
8232                     0.00          18.0            0.0  Autumn
8229                     0.00          18.0            0.0  Autumn

         Holiday Functioning Day
3997  No Holiday             Yes
6501  No Holiday             Yes
5132  No Holiday             Yes
5034  No Holiday             Yes
6524  No Holiday             Yes
4012  No Holiday             Yes
6498  No Holiday             Yes
5099  No Holiday             Yes
8232  No Holiday              No
8229  No Holiday             Yes

==================================================

Column: Snowfall (cm)
Number of Outliers: 443
Outliers Statistics:
count    443.000000
mean       1.484424
std        1.297372
min        0.100000
25%        0.500000
50%        1.000000
75%        2.200000
max        8.800000
Name: Snowfall (cm), dtype: float64
Top 10 Outliers in Snowfall (cm):
           day  date  month  year  Rented Bike Count  Hour  Temperature(°C)  \
8602  Saturday    24     11  2018                 62    10              0.4
8603  Saturday    24     11  2018                114    11              1.2
8601  Saturday    24     11  2018                 24     9              0.3
8604  Saturday    24     11  2018                167    12              2.5
8605  Saturday    24     11  2018                241    13              2.6
420     Monday    18     12  2017                 62    12             -1.8
421     Monday    18     12  2017                 76    13             -0.9
8606  Saturday    24     11  2018                298    14              3.0
418     Monday    18     12  2017                 36    10             -3.7
419     Monday    18     12  2017                 44    11             -2.9

      Humidity(%)  Wind speed (m/s)  Visibility (10m)  \
8602           97               1.8               207
8603           97               2.3               975
8601           97               3.0                34
8604           84               1.9              1538
8605           83               1.9              1774
420            83               1.2               351
421            84               1.2               333
8606           82               1.7              1589
418            87               1.0               541
419            85               1.2               243

      Solar Radiation (MJ/m2)  Rainfall(mm)  Snowfall (cm) Seasons  \
8602                     0.00           0.0            8.8  Autumn
8603                     0.07           0.0            8.8  Autumn
8601                     0.00           9.1            7.1  Autumn
8604                     0.40           1.8            7.0  Autumn
8605                     0.84           0.0            6.0  Autumn
420                      0.09           1.1            5.1  Winter
421                      0.09           0.0            5.0  Winter
8606                     0.55           0.0            5.0  Autumn
418                      0.03           0.0            4.8  Winter